from selenium.webdriver.common.by import By


class OrderPageLocators:
    BUTTON_LOGO_SCOOTER = [By.XPATH, './/a[@class="Header_LogoScooter__3lsAR"]']
    BUTTON_LOGO_YANDEX = [By.XPATH, './/a[@class="Header_LogoYandex__3TSOI"]']
    PANEL_ORDER = [By.XPATH, './/div[@class="Order_Content__bmtHS"]']
    INPUT_FIRST_NAME_FIELD = [By.XPATH, './/input[@placeholder="* Имя"]']
    INPUT_SECOND_NAME_FIELD = [By.XPATH, './/input[@placeholder="* Фамилия"]']
    INPUT_ADDRESS_FIELD = [By.XPATH, './/input[@placeholder="* Адрес: куда привезти заказ"]']
    INPUT_METRO_STATION_SEARCH = [By.XPATH, './/input[@placeholder="* Станция метро"]']
    SELECT_SEARCH_METRO_STATION = [By.XPATH, './/input[@placeholder="* Станция метро"]//*']
    BUTTON_STATE_1 = [By.XPATH, './/*[text()="Университет"]']
    BUTTON_STATE_2 = [By.XPATH, './/*[text()="ВДНХ"]']
    INPUT_PHONE_NUMBER_FIELD = [By.XPATH, './/input[@placeholder="* Телефон: на него позвонит курьер"]']
    BUTTON_NEXT = [By.XPATH, './/button[text()="Далее"]']
    INPUT_DELIVERY_DATE = [By.XPATH, './/input[@placeholder="* Когда привезти самокат"]']
    SELECT_05_05_25 = [By.XPATH, './/div[@aria-label="Choose понедельник, 5-е мая 2025 г."]']
    SELECT_10_05_25 = [By.XPATH, './/div[@aria-label="Choose суббота, 10-е мая 2025 г."]']
    SELECT_RENTAL_PERIOD = [By.XPATH, './/div[text()="* Срок аренды"]']
    OPTION_RENTAL_PERIOD_ONE_DAY = [By.XPATH, './/div[text()="сутки"]']
    OPTION_RENTAL_PERIOD_TWO_DAY = [By.XPATH, './/div[text()="двое суток"]']
    OPTION_RENTAL_PERIOD_THREE_DAY = [By.XPATH, './/div[text()="трое суток"]']
    OPTION_RENTAL_PERIOD_FOUR_DAY = [By.XPATH, './/div[text()="четверо суток"]']
    OPTION_RENTAL_PERIOD_FIVE_DAY = [By.XPATH, './/div[text()="пятеро суток"]']
    OPTION_RENTAL_PERIOD_SIX_DAY = [By.XPATH, './/div[text()="шестеро суток"]']
    OPTION_RENTAL_PERIOD_SEVEN_DAY = [By.XPATH, './/div[text()="семеро суток"]']
    CHECKBOX_BLACK_COLOR = [By.ID, 'black']
    CHECKBOX_GREY_COLOR = [By.ID, 'grey']
    INPUT_COMMENT_FOR_COURIER = [By.XPATH, './/input[@placeholder="Комментарий для курьера"]']
    BUTTON_MAKE_AN_ORDER = [By.XPATH, './/button[@class="Button_Button__ra12g Button_Middle__1CSJM"]']
    PANEL_CONFIRMATION_TO_ORDER = [By.XPATH, './/div[@class="Order_Modal__YZ-d3"]']
    BUTTON_ORDER = [By.XPATH, './/button[text()="Заказать"]']
    BUTTON_YES = [By.XPATH, './/button[text()="Да"]']
    BUTTON_NO = [By.XPATH, './/button[text()="Нет"]']
    PANEL_SUCCESSFUl_ORDER = [By.XPATH, './/div[@class="Order_ModalHeader__3FDaJ" and text()="Заказ оформлен"]']